name: Deploy project
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm ci
          echo "Successfully installed dependencies"
      - name: Lint
        run: |
          npm run lint
          echo "Successfully run lint"
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm ci
          echo "Successfully installed dependencies"
      - name: Test
        run: |
          npm run test
          echo "Successfully run tests"
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm ci
          echo "Successfully installed dependencies"
      - name: Build
        run: |
          npm run build
          echo "Successfully built project artifacts"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm ci
          echo "Successfully installed dependencies"
      - name: Deploy
        run: |
          echo "Deploying..."
          echo "Successfully deployed project artifacts"

