name: Output issue events
on:
  workflow_dispatch:
  issues:
jobs:
  output-issue-events:
    runs-on: ubuntu-latest
    steps:
      - name: Output issue create event output
        run: echo "${{ toJSON(github.event) || 'N/A' }}"

