name: Output issue events
on:
  workflow_dispatch:
  issues:
    types:
      - opened
jobs:
  output-issue-events:
    runs-on: ubuntu-latest
    steps:
      - name: Output issue create event output
        run: |
          echo "issue title ${{ toJSON(github.event.issue.title) }}"
          echo "issue body ${{ toJSON(github.event.issue.body) }}"

