name: Output issue events
on:
  issues:
    types: [ opened ]
jobs:
  output-issue-events:
    runs-on: ubuntu-latest
    steps:
      - name: Output issue create event output
        run: |
          echo "${{ toJSON(github.event) }}"

